#pragma once


#define DEBUG

#define POSITION_BUFFER_INDEX 0
#define NORMAL_BUFFER_INDEX 1
#define COLOR_BUFFER_INDEX 2
#define TEX_COORD_BUFFER_INDEX 3
#define BONE_ID_BUFFER_INDEX 4
#define BONE_WEIGHT_BUFFER_INDEX 5